# Generated by Django 2.2.7 on 2019-11-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.PositiveIntegerField(verbose_name='Доставка'),
        ),
    ]
