# Generated by Django 2.2.7 on 2019-11-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191130_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='curier',
        ),
    ]
