# Generated by Django 2.2.7 on 2019-11-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191130_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='curier',
            new_name='updated',
        ),
    ]
