# Generated by Django 2.2.7 on 2019-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191130_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.CharField(choices=[('GLOVO + 1000', 'GLOVO+1000'), ('YANDEX + 900', 'YANDEX+900'), ('WOLT + 1100', 'WOLT+1100')], default='GLOVO + 1000', max_length=10, verbose_name='Доставка'),
        ),
    ]
